### ISSUE TITLE
[Feature Request] Argument parser improvements

### ISSUE THREAD

**Issue by grian32** [harmonyland/harmony#190]
**What do you want to request?**
A few improvements with the arg parser:
 - Parses users into User objects, roles into Role objects etc
 - Also handles names, could return `false` if theres roles/users/channels with the same name so the bot dev can accurately send out an error message.

**Comment by MierenManz** [comment]
The first one is very possible and kinda stupid that we don't have that >.<

The second one will be alot harder because you would have to go through the guild cache.
Then go through all entries to find the correct name.

I think that will likely do more harm than good.

If anyone else has ideas on what to add.
Put them here so we can check them out and add them to a future pr updating the argument parser.

**Comment by grian32** [comment]
The second one I'm ehhhh about aswell just thought I'd include it in the request for completeness sake

**Comment by grian32** [comment]
@MierenManz Forgot to add in original issue, it would also handle mentions instead of only id's
